services:
  freeman-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: freeman_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - freeeman-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=20)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  freeman-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: freeeman_bot
    env_file:
      - ./bot/.env
    environment:
      API_URL: http://freeman-backend:8000
    depends_on:
      freeman-backend:
        condition: service_healthy
    networks:
      - freeeman-network
    restart: unless-stopped
  freeman-admin-bot:
    build:
      context: ./admin-bot
      dockerfile: Dockerfile
    container_name: freeeman_admin_bot
    env_file:
      - ./admin-bot/.env
    networks:
      - freeeman-network
    restart: unless-stopped
  freeman-minio:
    image: quay.io/minio/minio
    container_name: freeman-minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersecretpassword
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

networks:
  freeeman-network:
    driver: bridge
