"""added birth date and city

Revision ID: cde8e0f685df
Revises: 5d2819eb9a39
Create Date: 2026-04-23 13:37:48.153089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde8e0f685df'
down_revision: Union[str, Sequence[str], None] = '5d2819eb9a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core',
    sa.Column('activity', sa.Text(), nullable=True),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('priorities', sa.JSON(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('difficulties', sa.Text(), nullable=True),
    sa.Column('readiness', sa.String(length=255), nullable=True),
    sa.Column('weekly_time', sa.String(length=255), nullable=True),
    sa.Column('rules', sa.String(length=255), nullable=True),
    sa.Column('payment', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'city')
    op.drop_column('user', 'birth_date')
    op.drop_table('core')
    # ### end Alembic commands ###
