"""added description in diagnostic field

Revision ID: 62e3a4df5b82
Revises: 022ba7ac1893
Create Date: 2026-04-11 09:27:27.485776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e3a4df5b82'
down_revision: Union[str, Sequence[str], None] = '022ba7ac1893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnostics', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnostics', 'description')
    # ### end Alembic commands ###
